<?php $titlePage='Mon Super Blog' ?>

<h1 class="blue my-4">Bienvenue sur le blog de Gérald COL</h1>

<?php if (isset($_SESSION['username'])) : ?>
    <div class="alert alert-success">
        <li>Bienvenue <?= $_SESSION['username'] ?></li>
    </div>
<?php endif ?>

<p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dolore, cupiditate in suscipit voluptatum rerum perspiciatis odit sit expedita dolores reprehenderit vel animi atque deleniti sequi fugiat modi id aliquid eius enim dolorem adipisci pariatur. <img class="me" src="<?= SCRIPTS . 'pictures' . DIRECTORY_SEPARATOR . 'MRO_5839.jpg' ?>" alt="Gérald COL"> Beatae natus asperiores vel libero iste! Nulla provident assumenda ea aliquam eos, fuga laboriosam corrupti voluptates! Magni rem quas minus aperiam quae laudantium blanditiis, ex tempore quod omnis aliquid provident illo sunt nesciunt sint voluptatum accusamus sequi accusantium beatae optio illum aspernatur enim quam. Fugit tempora dolores reprehenderit temporibus nesciunt similique dolorem illo alias, consequuntur, molestias saepe perspiciatis eius. Aliquam ab unde quasi illo qui a expedita ipsam saepe quidem maxime atque magnam maiores, doloremque necessitatibus eveniet enim nulla repellat nemo, consectetur, cumque consequatur? Totam dolor sunt eveniet, excepturi placeat id, mollitia numquam soluta minus velit iure fuga perspiciatis deserunt quam? Obcaecati suscipit neque voluptatibus, facere odit earum corporis iste saepe sit, odio laboriosam nisi error velit sequi, omnis ad! Vel quasi temporibus corporis asperiores amet ab exercitationem, excepturi molestias consequuntur ducimus suscipit dicta cumque vero officia corrupti totam laborum cupiditate nemo. Natus atque expedita adipisci minus ipsa officiis rem, iusto architecto quod quis, accusamus eos vitae et quia sapiente quos aspernatur, porro voluptatem laboriosam dolorum dolor. Distinctio nostrum suscipit harum at aliquam qui magnam eaque recusandae enim velit, omnis debitis minima, sapiente veniam praesentium, eius possimus modi. Necessitatibus explicabo ullam, asperiores, numquam non molestias blanditiis labore molestiae aspernatur assumenda neque autem facere maiores tempore a. Illo, doloremque aliquam. Nemo veritatis corrupti minima voluptatibus quis sint?</p>
<p class="text-center"><a href="<?= SCRIPTS . 'documents' . DIRECTORY_SEPARATOR . 'cv_2021.pdf' ?>" download="cv_de_Mr_Gerald_Col.pdf" title="Télécharger mon CV" target="_blank"><button class="btn btn-primary">Mon CV</button></a></p>
<div class="row">
    <div class="col-sm-6 col-md-4 my-4"><div style="padding:56.25% 0 0 0;position:relative;"><iframe src="https://player.vimeo.com/video/607803175?loop=1&autopause=0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen frameborder="0" style="position:absolute;top:0;left:0;width:100%;height:100%;"></iframe></div></div>
    <div class="col-sm-6 col-md-4 my-4"><div style="padding:56.25% 0 0 0;position:relative;"><iframe src="https://player.vimeo.com/video/607803591?loop=1&autopause=0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen frameborder="0" style="position:absolute;top:0;left:0;width:100%;height:100%;"></iframe></div></div>
    <div class="col-sm-6 col-md-4 my-4"><div style="padding:56.25% 0 0 0;position:relative;"><iframe src="https://player.vimeo.com/video/607803868?loop=1&autopause=0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen frameborder="0" style="position:absolute;top:0;left:0;width:100%;height:100%;"></iframe></div></div>
</div>
<p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dolore, cupiditate in suscipit voluptatum rerum perspiciatis odit sit expedita dolores reprehenderit vel animi atque deleniti sequi fugiat modi id aliquid eius enim dolorem adipisci pariatur. Beatae natus asperiores vel libero iste! Nulla provident assumenda ea aliquam eos, fuga laboriosam corrupti voluptates! Magni rem quas minus aperiam quae laudantium blanditiis, ex tempore quod omnis aliquid provident illo sunt nesciunt sint voluptatum accusamus sequi accusantium beatae optio illum aspernatur enim quam. Fugit tempora dolores reprehenderit temporibus nesciunt similique dolorem illo alias, consequuntur, molestias saepe perspiciatis eius. Aliquam ab unde quasi illo qui a expedita ipsam saepe quidem maxime atque magnam maiores, doloremque necessitatibus eveniet enim nulla repellat nemo, consectetur, cumque consequatur? Totam dolor sunt eveniet, excepturi placeat id, mollitia numquam soluta minus velit iure fuga perspiciatis deserunt quam? Obcaecati suscipit neque voluptatibus, facere odit earum corporis iste saepe sit, odio laboriosam nisi error velit sequi, omnis ad! Vel quasi temporibus corporis asperiores amet ab exercitationem, excepturi molestias consequuntur ducimus suscipit dicta cumque vero officia corrupti totam laborum cupiditate nemo. Natus atque expedita adipisci minus ipsa officiis rem, iusto architecto quod quis, accusamus eos vitae et quia sapiente quos aspernatur, porro voluptatem laboriosam dolorum dolor. Distinctio nostrum suscipit harum at aliquam qui magnam eaque recusandae enim velit, omnis debitis minima, sapiente veniam praesentium, eius possimus modi. Necessitatibus explicabo ullam, asperiores, numquam non molestias blanditiis labore molestiae aspernatur assumenda neque autem facere maiores tempore a. Illo, doloremque aliquam. Nemo veritatis corrupti minima voluptatibus quis sint?</p>